# Alembic initialization config
[alembic]
sqlalchemy.url = 
sqlalchemy.echo = false
version_path_separator = :
version_locations = %(here)s/versions
file_template = %%(rev)s_%%(slug)s
date_format = %%(rev)s_%%(epoch)s

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
